version: '3.0'

services:
  nginx:
    image: nginx
    restart: always
    volumes:
      - ./docker/nginx/conf.d/default.nginx:/etc/nginx/conf.d/default.conf
      - ./frontend/dist/:/var/www/html/
    ports:
      - 80:80
    networks:
      mynet:
        ipv4_address: 172.16.238.4
  api:
    build: './api'
    restart: always
    ports:
      - 4000:4000
    volumes:
      - ./api.env:/usr/src/app/.env
    networks:
      mynet:
        ipv4_address: 172.16.238.3
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: "test"
      POSTGRES_USER: andrey
      POSTGRES_PASSWORD: pass
    # volumes:
    #   - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
    networks:
      mynet:
        ipv4_address: 172.16.238.2
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      mynet:
        ipv4_address: 172.16.238.5

networks:
  mynet:
    driver: bridge
    internal: false
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
